{
    'name': 'Nephro Core',
    'version': '19.0.2.0.0',
    'category': 'Healthcare',
    'summary': 'Core models for nephrology HMS: patient, physician, procedure, appointment, prescription',
    'author': 'As-Shafi Medical',
    'website': 'https://as-shafi.com',
    'license': 'LGPL-3',
    'depends': ['base', 'mail', 'product', 'stock', 'contacts'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'security/security_rules.xml',
        'data/sequence_data.xml',
        'views/patient_views.xml',
        'views/physician_views.xml',
        'views/procedure_views.xml',
        'views/appointment_views.xml',
        'views/prescription_views.xml',
        'views/menu_items.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}
